.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. cscoin_qt test_cscoin_qt
clean: FORCE
	$(MAKE) -C .. cscoin_qt_clean test_cscoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_cscoin_qt_check
cscoin-qt cscoin-qt.exe: FORCE
	 $(MAKE) -C .. cscoin_qt
apk: FORCE
	$(MAKE) -C .. cscoin_qt_apk
